#!/usr/bin/env bash

# ccx utility by Faraz Syed <hello@farazsyed.com>
#
# Used to quickly test small C++ files
#
# Usage: ccx <filepath> [<args>]
#
# License: MIT

if [ "${1}" = "--verbose" ] || [ "${1}" = "-v" ]; then
  VERBOSE="true"
  NAME="${2}"
  ARGS="${@:3}"
else
  VERBOSE="false"
  NAME="${1}"
  ARGS="${@:2}"
fi

# print usage information
if [ ! "${NAME}" ]; then
  echo "ccx is a tool for running simple C++ files

Usage: ccx <filepath> [<args>]"
  exit 0
fi

TEMP_FILE="$(mktemp)"

function info() {
  [ "${VERBOSE}" = "true" ] && >&2 echo ${@}
}

info "Compile."
g++ -g -Wall -o "${TEMP_FILE}" "${NAME}"

info "Configure permissions."
chmod +x "${TEMP_FILE}"

info "Execute."
info "Preview:" "${NAME}" "${ARGS}"
"${TEMP_FILE}" ${ARGS}

info "Clean up."
rm -f "${TEMP_FILE}"
